@startuml
skinparam linetype polyline

component "context" as context #LightGreen
Component "mem" as mem #LightGreen

component "shader" as shader #LightGreen
component "sync" as sync #LightGreen
component "buf" as buf #LightGreen
component "img" as img #LightGreen
component "bvh" as bvh #LightGreen
component "swapchain" as swapchain #DarkOrange


component "stage" as stage #LightGreen
component "cmd" as cmd #LightGreen
component "queue" as queue #DarkOrange
component "gc" as gc #LightGreen


component "dma" as dma #Red
component "heap" as heap #Red

component "heapctl" as heapctl #Red

[shader] --> [context]
[sync] --> [context]
[mem] --> [context]

[buf] --> [mem]
[img] --> [mem]

[bvh] --> [buf]

[stage] --> [buf]

[cmd] --> [buf]
[cmd] --> [img]
[cmd] --> [bvh]
[cmd] --> [shader]
[cmd] --> [stage]

[cmd] --> [heap]
[cmd] --> [sync]

[swapchain] --> [img]
[swapchain] --> [sync]
[queue] --> [swapchain]

[queue] --> [gc]
[gc] --> [sync]
[gc] --> [cmd]
[queue] -> [cmd]
[queue] -> [sync]

[dma] --> [queue]
[dma] --> [stage]
[dma] --> [cmd]

[heap] --> [buf]
[heapctl] --> [heap]
[heapctl] --> [dma]
[heapctl] --> [queue]

@enduml
