-- Inserts a Doxygen group generated by the same build.
--
-- Markdown usage:
--
--   ::: {.doxygen group="rhi"}
--   :::
--
-- Group names are intentionally restricted to Doxygen's stable group__<name>
-- filename convention.  Keep them semantic and declare them in code with
-- \defgroup rhi ... and \ingroup rhi.

function Div(div)
  if not div.classes:includes("doxygen") then
    return nil
  end

  local group = div.attributes["group"]
  if group == nil or not group:match("^[A-Za-z0-9_]+$") then
    error("A doxygen div requires group=\"[A-Za-z0-9_]+\".")
  end
  if #div.content ~= 0 then
    error("A doxygen div is an insertion marker and must be empty.")
  end

  return pandoc.RawBlock("latex", "\\input{doxygen/latex/group__" .. group .. ".tex}")
end
