#include "strobe/imgui/platform/keyboard.hpp"

namespace strobe::imgui::platform {

ImGuiKey Keyboard::to_imgui_key(strobe::platform::Key key) noexcept {
  using Key = strobe::platform::Key;

  switch (key) {
  case Key::unknown:
    return ImGuiKey_None;
  case Key::space:
    return ImGuiKey_Space;
  case Key::apostrophe:
    return ImGuiKey_Apostrophe;
  case Key::comma:
    return ImGuiKey_Comma;
  case Key::minus:
    return ImGuiKey_Minus;
  case Key::period:
    return ImGuiKey_Period;
  case Key::slash:
    return ImGuiKey_Slash;
  case Key::num_0:
    return ImGuiKey_0;
  case Key::num_1:
    return ImGuiKey_1;
  case Key::num_2:
    return ImGuiKey_2;
  case Key::num_3:
    return ImGuiKey_3;
  case Key::num_4:
    return ImGuiKey_4;
  case Key::num_5:
    return ImGuiKey_5;
  case Key::num_6:
    return ImGuiKey_6;
  case Key::num_7:
    return ImGuiKey_7;
  case Key::num_8:
    return ImGuiKey_8;
  case Key::num_9:
    return ImGuiKey_9;
  case Key::semicolon:
    return ImGuiKey_Semicolon;
  case Key::equal:
    return ImGuiKey_Equal;

  case Key::a:
    return ImGuiKey_A;
  case Key::b:
    return ImGuiKey_B;
  case Key::c:
    return ImGuiKey_C;
  case Key::d:
    return ImGuiKey_D;
  case Key::e:
    return ImGuiKey_E;
  case Key::f:
    return ImGuiKey_F;
  case Key::g:
    return ImGuiKey_G;
  case Key::h:
    return ImGuiKey_H;
  case Key::i:
    return ImGuiKey_I;
  case Key::j:
    return ImGuiKey_J;
  case Key::k:
    return ImGuiKey_K;
  case Key::l:
    return ImGuiKey_L;
  case Key::m:
    return ImGuiKey_M;
  case Key::n:
    return ImGuiKey_N;
  case Key::o:
    return ImGuiKey_O;
  case Key::p:
    return ImGuiKey_P;
  case Key::q:
    return ImGuiKey_Q;
  case Key::r:
    return ImGuiKey_R;
  case Key::s:
    return ImGuiKey_S;
  case Key::t:
    return ImGuiKey_T;
  case Key::u:
    return ImGuiKey_U;
  case Key::v:
    return ImGuiKey_V;
  case Key::w:
    return ImGuiKey_W;
  case Key::x:
    return ImGuiKey_X;
  case Key::y:
    return ImGuiKey_Y;
  case Key::z:
    return ImGuiKey_Z;

  case Key::left_bracket:
    return ImGuiKey_LeftBracket;
  case Key::backslash:
    return ImGuiKey_Backslash;
  case Key::right_bracket:
    return ImGuiKey_RightBracket;
  case Key::grave_accent:
    return ImGuiKey_GraveAccent;

  case Key::world_1:
  case Key::world_2:
    return ImGuiKey_None;

  case Key::escape:
    return ImGuiKey_Escape;
  case Key::enter:
    return ImGuiKey_Enter;
  case Key::tab:
    return ImGuiKey_Tab;
  case Key::backspace:
    return ImGuiKey_Backspace;
  case Key::insert:
    return ImGuiKey_Insert;
  case Key::del:
    return ImGuiKey_Delete;
  case Key::right:
    return ImGuiKey_RightArrow;
  case Key::left:
    return ImGuiKey_LeftArrow;
  case Key::down:
    return ImGuiKey_DownArrow;
  case Key::up:
    return ImGuiKey_UpArrow;
  case Key::page_up:
    return ImGuiKey_PageUp;
  case Key::page_down:
    return ImGuiKey_PageDown;
  case Key::home:
    return ImGuiKey_Home;
  case Key::end:
    return ImGuiKey_End;

  case Key::caps_lock:
    return ImGuiKey_CapsLock;
  case Key::scroll_lock:
    return ImGuiKey_ScrollLock;
  case Key::num_lock:
    return ImGuiKey_NumLock;
  case Key::print_screen:
    return ImGuiKey_PrintScreen;
  case Key::pause:
    return ImGuiKey_Pause;

  case Key::f1:
    return ImGuiKey_F1;
  case Key::f2:
    return ImGuiKey_F2;
  case Key::f3:
    return ImGuiKey_F3;
  case Key::f4:
    return ImGuiKey_F4;
  case Key::f5:
    return ImGuiKey_F5;
  case Key::f6:
    return ImGuiKey_F6;
  case Key::f7:
    return ImGuiKey_F7;
  case Key::f8:
    return ImGuiKey_F8;
  case Key::f9:
    return ImGuiKey_F9;
  case Key::f10:
    return ImGuiKey_F10;
  case Key::f11:
    return ImGuiKey_F11;
  case Key::f12:
    return ImGuiKey_F12;
  case Key::f13:
    return ImGuiKey_F13;
  case Key::f14:
    return ImGuiKey_F14;
  case Key::f15:
    return ImGuiKey_F15;
  case Key::f16:
    return ImGuiKey_F16;
  case Key::f17:
    return ImGuiKey_F17;
  case Key::f18:
    return ImGuiKey_F18;
  case Key::f19:
    return ImGuiKey_F19;
  case Key::f20:
    return ImGuiKey_F20;
  case Key::f21:
    return ImGuiKey_F21;
  case Key::f22:
    return ImGuiKey_F22;
  case Key::f23:
    return ImGuiKey_F23;
  case Key::f24:
    return ImGuiKey_F24;
  case Key::f25:
    return ImGuiKey_None;

  case Key::keypad_0:
    return ImGuiKey_Keypad0;
  case Key::keypad_1:
    return ImGuiKey_Keypad1;
  case Key::keypad_2:
    return ImGuiKey_Keypad2;
  case Key::keypad_3:
    return ImGuiKey_Keypad3;
  case Key::keypad_4:
    return ImGuiKey_Keypad4;
  case Key::keypad_5:
    return ImGuiKey_Keypad5;
  case Key::keypad_6:
    return ImGuiKey_Keypad6;
  case Key::keypad_7:
    return ImGuiKey_Keypad7;
  case Key::keypad_8:
    return ImGuiKey_Keypad8;
  case Key::keypad_9:
    return ImGuiKey_Keypad9;
  case Key::keypad_decimal:
    return ImGuiKey_KeypadDecimal;
  case Key::keypad_divide:
    return ImGuiKey_KeypadDivide;
  case Key::keypad_multiply:
    return ImGuiKey_KeypadMultiply;
  case Key::keypad_subtract:
    return ImGuiKey_KeypadSubtract;
  case Key::keypad_add:
    return ImGuiKey_KeypadAdd;
  case Key::keypad_enter:
    return ImGuiKey_KeypadEnter;
  case Key::keypad_equal:
    return ImGuiKey_KeypadEqual;

  case Key::left_shift:
    return ImGuiKey_LeftShift;
  case Key::left_control:
    return ImGuiKey_LeftCtrl;
  case Key::left_alt:
    return ImGuiKey_LeftAlt;
  case Key::left_super:
    return ImGuiKey_LeftSuper;
  case Key::right_shift:
    return ImGuiKey_RightShift;
  case Key::right_control:
    return ImGuiKey_RightCtrl;
  case Key::right_alt:
    return ImGuiKey_RightAlt;
  case Key::right_super:
    return ImGuiKey_RightSuper;
  case Key::menu:
    return ImGuiKey_Menu;
  }

  std::terminate();
}
} // namespace strobe::imgui::platform
