@startuml
!include ./theme.puml

SwapchainFboSrcPass : 
DrawTrianglePass :
SwapchainFboDestPass : 

SwapchainFboSrcPass --> DrawTrianglePass : Framebuffer

DrawTrianglePass --> SwapchainFboDestPass : Framebuffer


@enduml
