@startuml
!include ./theme.puml


AcquireSwapchainFramePass :
AcquireGraphicsQueuePass : 
CmdPoolSourcePass :
ResetCmdPoolPass : 
AllocateCmdBufferPass : 
BeginCmdBuffPass :
EndCmdBuffPass :
TriangleRenderPass : 
SubmitCmdBufferPass:
PresentQueuePass :
RenderPassSourcePass :
FramebufferCachedSourcePass: 
PipelineLayoutSourcePass : 


CmdPoolSourcePass --> ResetCmdPoolPass : pool
ResetCmdPoolPass --> AllocateCmdBufferPass : pool
AllocateCmdBufferPass --> BeginCmdBuffPass : cbuff
BeginCmdBuffPass --> TriangleRenderPass : cbuff
TriangleRenderPass --> EndCmdBuffPass : cbuff
EndCmdBuffPass --> SubmitCmdBufferPass : cbuff
SubmitCmdBufferPass --> PresentQueuePass : renderingDoneSemaphore


AcquireGraphicsQueuePass --> SubmitCmdBufferPass : queue
AcquireGraphicsQueuePass --> PresentQueuePass : queue

RenderPassSourcePass --> TriangleRenderPass : renderPass

RenderPassSourcePass --> FramebufferCachedSourcePass : renderPass
FramebufferCachedSourcePass --> TriangleRenderPass : framebuffer

AcquireSwapchainFramePass --> FramebufferCachedSourcePass : imageView

PipelineLayoutSourcePass --> TriangleRenderPass : pipelineLayout

AcquireSwapchainFramePass --> SubmitCmdBufferPass : imageAvaiableSemaphore




@enduml
