@startuml
!include ./bindables.puml

class VulkanShader extends Shader{

}

class VulkanTexture2D extends Texture2D{

}

class VulkanUniformBuffer extends UniformBuffer{

}

class VulkanIndexBuffer extends IndexBuffer{

}

class VulkanVertexBuffer extends VertexBuffer{
}

class VulkanVertexArrayBuffer extends VertexArrayBuffer{}

@enduml
