@startuml

!include ./resources.puml

class VulkanFramebuffer extends Resource{
}

class VulkanDevice extends Resource{

}

class VulkanPDevice extends Resource{

}

class VulkanRenderInstance extends Resource{

}

class VulkanSwapchain extends Resource{

}

class VulkanRenderQueue extends Resource{

}

class VulkanCommandBuffer extends Resource{

}


@enduml
