#pragma once

namespace sge {

typedef int action_t;

typedef int button_t;
#define STROBE_MOUSE_BUTTON_1 0
#define STROBE_MOUSE_BUTTON_2 1
#define STROBE_MOUSE_BUTTON_3 2
#define STROBE_MOUSE_BUTTON_4 3
#define STROBE_MOUSE_BUTTON_5 4
#define STROBE_MOUSE_BUTTON_6 5
#define STROBE_MOUSE_BUTTON_7 6
#define STROBE_MOUSE_BUTTON_8 7
#define STROBE_MOUSE_BUTTON_LAST STROBE_MOUSE_BUTTON_8
#define STROBE_MOUSE_BUTTON_LEFT STROBE_MOUSE_BUTTON_1
#define STROBE_MOUSE_BUTTON_RIGHT STROBE_MOUSE_BUTTON_2
#define STROBE_MOUSE_BUTTON_MIDDLE STROBE_MOUSE_BUTTON_MIDDLE

typedef int key_t;
#define STROBE_KEY_UNKNOWN -1
#define STROBE_KEY_SPACE 32
#define STROBE_KEY_APOSTROPHE 39 /* ' */
#define STROBE_KEY_COMMA 44      /* , */
#define STROBE_KEY_MINUS 45      /* - */
#define STROBE_KEY_PERIOD 46     /* . */
#define STROBE_KEY_SLASH 47      /* / */
#define STROBE_KEY_0 48
#define STROBE_KEY_1 49
#define STROBE_KEY_2 50
#define STROBE_KEY_3 51
#define STROBE_KEY_4 52
#define STROBE_KEY_5 53
#define STROBE_KEY_6 54
#define STROBE_KEY_7 55
#define STROBE_KEY_8 56
#define STROBE_KEY_9 57
#define STROBE_KEY_SEMICOLON 59 /* ; */
#define STROBE_KEY_EQUAL 61     /* = */
#define STROBE_KEY_A 65
#define STROBE_KEY_B 66
#define STROBE_KEY_C 67
#define STROBE_KEY_D 68
#define STROBE_KEY_E 69
#define STROBE_KEY_F 70
#define STROBE_KEY_G 71
#define STROBE_KEY_H 72
#define STROBE_KEY_I 73
#define STROBE_KEY_J 74
#define STROBE_KEY_K 75
#define STROBE_KEY_L 76
#define STROBE_KEY_M 77
#define STROBE_KEY_N 78
#define STROBE_KEY_O 79
#define STROBE_KEY_P 80
#define STROBE_KEY_Q 81
#define STROBE_KEY_R 82
#define STROBE_KEY_S 83
#define STROBE_KEY_T 84
#define STROBE_KEY_U 85
#define STROBE_KEY_V 86
#define STROBE_KEY_W 87
#define STROBE_KEY_X 88
#define STROBE_KEY_Y 89
#define STROBE_KEY_Z 90
#define STROBE_KEY_LEFT_BRACKET 91
#define STROBE_KEY_BACKSLASH 92
#define STROBE_KEY_RIGHT_BRACKET 93
#define STROBE_KEY_GRAVE_ACCENT 96
#define STROBE_KEY_WORLD_1 161
#define STROBE_KEY_WORLD_2 162
#define STROBE_KEY_ESCAPE 256
#define STROBE_KEY_ENTER 257
#define STROBE_KEY_TAB 258
#define STROBE_KEY_BACKSPACE 259
#define STROBE_KEY_INSERT 260
#define STROBE_KEY_DELETE 261
#define STROBE_KEY_RIGHT 262
#define STROBE_KEY_LEFT 263
#define STROBE_KEY_DOWN 264
#define STROBE_KEY_UP 265
#define STROBE_KEY_PAGE_UP 266
#define STROBE_KEY_PAGE_DOWN 267
#define STROBE_KEY_HOME 268
#define STROBE_KEY_END 269
#define STROBE_KEY_CAPS_LOCK 280
#define STROBE_KEY_SCROLL_LOCK 281
#define STROBE_KEY_NUM_LOCK 282
#define STROBE_KEY_PRINT_SCREEN 283
#define STROBE_KEY_PAUSE 284
#define STROBE_KEY_F1 290
#define STROBE_KEY_F2 291
#define STROBE_KEY_F3 292
#define STROBE_KEY_F4 293
#define STROBE_KEY_F5 294
#define STROBE_KEY_F6 295
#define STROBE_KEY_F7 296
#define STROBE_KEY_F8 297
#define STROBE_KEY_F9 298
#define STROBE_KEY_F10 299
#define STROBE_KEY_F11 300
#define STROBE_KEY_F12 301
#define STROBE_KEY_F13 302
#define STROBE_KEY_F14 303
#define STROBE_KEY_F15 304
#define STROBE_KEY_F16 305
#define STROBE_KEY_F17 306
#define STROBE_KEY_F18 307
#define STROBE_KEY_F19 308
#define STROBE_KEY_F20 309
#define STROBE_KEY_F21 310
#define STROBE_KEY_F22 311
#define STROBE_KEY_F23 312
#define STROBE_KEY_F24 313
#define STROBE_KEY_F25 314
#define STROBE_KEY_KP_0 320
#define STROBE_KEY_KP_1 321
#define STROBE_KEY_KP_2 322
#define STROBE_KEY_KP_3 323
#define STROBE_KEY_KP_4 324
#define STROBE_KEY_KP_5 325
#define STROBE_KEY_KP_6 326
#define STROBE_KEY_KP_7 327
#define STROBE_KEY_KP_8 328
#define STROBE_KEY_KP_9 329
#define STROBE_KEY_KP_DECIMAL 330
#define STROBE_KEY_KP_DIVIDE 331
#define STROBE_KEY_KP_MULTIPLY 332
#define STROBE_KEY_KP_SUBTRACT 333
#define STROBE_KEY_KP_ADD 334
#define STROBE_KEY_KP_ENTER 335
#define STROBE_KEY_KP_EQUAL 336
#define STROBE_KEY_LEFT_SHIFT 340
#define STROBE_KEY_LEFT_CONTROL 341
#define STROBE_KEY_LEFT_ALT 342
#define STROBE_KEY_LEFT_SUPER 343
#define STROBE_KEY_RIGHT_SHIFT 344
#define STROBE_KEY_RIGHT_CONTROL 345
#define STROBE_KEY_RIGHT_ALT 346
#define STROBE_KEY_RIGHT_SUPER 347
#define STROBE_KEY_MENU 348
#define STROBE_KEY_LAST STROBE_KEY_MENU

}  // namespace sge
