#pragma once

#include <fmt/format.h>
#include <vulkan/vulkan_core.h>
namespace strobe::rhi {

[[nodiscard]]
constexpr std::string_view vulkan_result_name(VkResult result) noexcept {
#define STROBE_VK_RESULT_CASE(value)                                           \
  case value:                                                                  \
    return #value

  switch (result) {
    STROBE_VK_RESULT_CASE(VK_SUCCESS);
    STROBE_VK_RESULT_CASE(VK_NOT_READY);
    STROBE_VK_RESULT_CASE(VK_TIMEOUT);
    STROBE_VK_RESULT_CASE(VK_EVENT_SET);
    STROBE_VK_RESULT_CASE(VK_EVENT_RESET);
    STROBE_VK_RESULT_CASE(VK_INCOMPLETE);

    STROBE_VK_RESULT_CASE(VK_ERROR_OUT_OF_HOST_MEMORY);
    STROBE_VK_RESULT_CASE(VK_ERROR_OUT_OF_DEVICE_MEMORY);
    STROBE_VK_RESULT_CASE(VK_ERROR_INITIALIZATION_FAILED);
    STROBE_VK_RESULT_CASE(VK_ERROR_DEVICE_LOST);
    STROBE_VK_RESULT_CASE(VK_ERROR_MEMORY_MAP_FAILED);
    STROBE_VK_RESULT_CASE(VK_ERROR_LAYER_NOT_PRESENT);
    STROBE_VK_RESULT_CASE(VK_ERROR_EXTENSION_NOT_PRESENT);
    STROBE_VK_RESULT_CASE(VK_ERROR_FEATURE_NOT_PRESENT);
    STROBE_VK_RESULT_CASE(VK_ERROR_INCOMPATIBLE_DRIVER);
    STROBE_VK_RESULT_CASE(VK_ERROR_TOO_MANY_OBJECTS);
    STROBE_VK_RESULT_CASE(VK_ERROR_FORMAT_NOT_SUPPORTED);
    STROBE_VK_RESULT_CASE(VK_ERROR_FRAGMENTED_POOL);
    STROBE_VK_RESULT_CASE(VK_ERROR_UNKNOWN);
    STROBE_VK_RESULT_CASE(VK_ERROR_VALIDATION_FAILED);
    STROBE_VK_RESULT_CASE(VK_ERROR_OUT_OF_POOL_MEMORY);
    STROBE_VK_RESULT_CASE(VK_ERROR_INVALID_EXTERNAL_HANDLE);
    STROBE_VK_RESULT_CASE(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
    STROBE_VK_RESULT_CASE(VK_ERROR_FRAGMENTATION);
    STROBE_VK_RESULT_CASE(VK_PIPELINE_COMPILE_REQUIRED);
    STROBE_VK_RESULT_CASE(VK_ERROR_NOT_PERMITTED);

    STROBE_VK_RESULT_CASE(VK_ERROR_SURFACE_LOST_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
    STROBE_VK_RESULT_CASE(VK_SUBOPTIMAL_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_OUT_OF_DATE_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_INVALID_SHADER_NV);

    STROBE_VK_RESULT_CASE(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR);

    STROBE_VK_RESULT_CASE(
        VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
    STROBE_VK_RESULT_CASE(VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT);
    STROBE_VK_RESULT_CASE(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);

    STROBE_VK_RESULT_CASE(VK_THREAD_IDLE_KHR);
    STROBE_VK_RESULT_CASE(VK_THREAD_DONE_KHR);
    STROBE_VK_RESULT_CASE(VK_OPERATION_DEFERRED_KHR);
    STROBE_VK_RESULT_CASE(VK_OPERATION_NOT_DEFERRED_KHR);

    STROBE_VK_RESULT_CASE(VK_ERROR_COMPRESSION_EXHAUSTED_EXT);
    STROBE_VK_RESULT_CASE(VK_INCOMPATIBLE_SHADER_BINARY_EXT);
    STROBE_VK_RESULT_CASE(VK_PIPELINE_BINARY_MISSING_KHR);
    STROBE_VK_RESULT_CASE(VK_ERROR_NOT_ENOUGH_SPACE_KHR);

    STROBE_VK_RESULT_CASE(VK_RESULT_MAX_ENUM);
  }

#undef STROBE_VK_RESULT_CASE

  return "VK_RESULT_UNKNOWN_VALUE";
}

template <typename... Args>
[[noreturn]] void vulkan_error(VkResult result, fmt::format_string<Args...> format,
                  Args &&...args) {
  fmt::println("[{}]: {}", vulkan_result_name(result),
               fmt::format(format, std::forward<Args>(args)...));
  std::terminate();
}

} // namespace strobe::rhi
